# Generated by Django 4.1.1 on 2022-09-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сайта')),
                ('description', models.TextField(verbose_name='Описание сайта')),
                ('logo', models.ImageField(upload_to='logo/')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Ссылка на страницу facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Ссылка на страницу instagram')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Ссылка на страницу linkedin')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Ссылка на страницу twitter')),
                ('skype', models.URLField(blank=True, null=True, verbose_name='Ссылка на skype')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Ссылка на telegram')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='Ссылка на whatsapp')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
